# BizGenius DigitalOcean App Platform Specification
# Deploy: doctl apps create --spec .do/app.yaml

name: bizgenius

region: nyc

# Services
services:
  # Frontend Static Site
  - name: frontend
    dockerfile_path: frontend/Dockerfile
    source_dir: frontend
    github:
      repo: acg-data/bizgenius
      branch: main
      deploy_on_push: true

    instance_count: 1
    instance_size_slug: basic-xxs

    http_port: 80

    routes:
      - path: /

    envs:
      - key: VITE_CONVEX_URL
        value: ${CONVEX_URL}
      - key: VITE_SENTRY_DSN
        value: ${SENTRY_DSN}

    alerts:
      - rule: DEPLOYMENT_FAILED
      - rule: DOMAIN_FAILED

# Domains (configure after initial deployment)
# domains:
#   - domain: bizgenius.app
#     type: PRIMARY
#   - domain: www.bizgenius.app
#     type: ALIAS

# Alerts
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
