"""Add generation sessions and OAuth tables

Revision ID: 2869a43e4924
Revises: 001_initial
Create Date: 2025-12-28 19:12:56.110191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2869a43e4924'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ideas_user_id_fkey'), 'ideas', type_='foreignkey')
    op.create_foreign_key(None, 'ideas', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('payments_user_id_fkey'), 'payments', type_='foreignkey')
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.create_foreign_key(op.f('payments_user_id_fkey'), 'payments', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'ideas', type_='foreignkey')
    op.create_foreign_key(op.f('ideas_user_id_fkey'), 'ideas', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
